services:
  - type: web
    name: beste-versie
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: YOUTUBE_API_KEY_1
        sync: false
      - key: YOUTUBE_API_KEY_2
        sync: false
      - key: YOUTUBE_API_KEY_3
        sync: false
      - key: YOUTUBE_API_KEY_4
        sync: false
      - key: YOUTUBE_API_KEY_5
        sync: false
      - key: YOUTUBE_API_KEY_6
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 3000
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_AUTH_TOKEN
        sync: false
